// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSQLConfig;

#nullable disable

namespace PostgreSQLDb.Migrations
{
    [DbContext(typeof(EducationPageDbContext))]
    [Migration("20240407100630_AddedThemesTable")]
    partial class AddedThemesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationPageWebAPI.Models.Article", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeId")
                        .HasColumnType("text");

                    b.HasKey("ArticleId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = "13adf83f-679b-4977-a48f-0fc363b8b75d",
                            Annotation = "This article is made to test the db connection",
                            Name = "Init article",
                            Text = "This article is very interesting, testing. This article is very interesting, testing.\nThis article is very interesting, testing. This article is very interesting, testing.\nThis article is very interesting, testing. This article is very interesting, testing.\nThis article is very interesting, testing. This article is very interesting, testing.\nThis article is very interesting, testing. This article is very interesting, testing.\nThis article is very interesting, testing. This article is very interesting, testing."
                        });
                });

            modelBuilder.Entity("Models.Models.Theme", b =>
                {
                    b.Property<string>("ThemeId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Icon")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("EducationPageWebAPI.Models.Article", b =>
                {
                    b.HasOne("Models.Models.Theme", "Theme")
                        .WithMany("Articles")
                        .HasForeignKey("ThemeId");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Models.Models.Theme", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
